FROM node:18.19.0

ENV PNPM_VERSION='8.14.2'

RUN apt update && \
    apt upgrade -y --no-install-recommends && \
    npm i --global --no-update-notifier --no-fund pnpm@${PNPM_VERSION}

WORKDIR /var/www/html
