#import "./application.fragment.gql"

mutation ApplicationUpdate($userApplication: UpdateUserApplicationInput) {
  userApplicationsUpdate(userApplication: $userApplication) {
    ...Application
  }
}
